# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284b857ce33e81ff94482b22d72ffb53009f279f67c0eaac3ef2971984c6772721564c3d5468123176dca7344cb56a1208c00170b4bf5a2fc9413b3ddcb81931

test:
  secret_key_base: b7d9bf08fa9747c95000ebc21d47b48dfcd60b1b561072af42d9fdd3466e2b95851b9ff6e0556acef07c179153a79972d95d63bc0601bad01d504621d16fb4b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
